package views;

import controller.CTDonXuatDao;
import controller.SanPhamDao;
import model.CTDonXuat;
import model.SanPham;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class CTDonXuatFrame extends javax.swing.JDialog {

    private DonXuatFrame home;
    private String maDonXuat = null;
    private ArrayList<SanPham> dsSanPham = new ArrayList<>();
    private String[] dsTenSanPham;
    private DefaultTableModel model;
    private final String[] tieuDe = {"STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng xuất"};
    private ArrayList<CTDonXuat> dsCTDonXuat = new ArrayList<>();
    private int viTri;

    /**
     * Creates new form CTPhieuNhapFrame
     */
    public CTDonXuatFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        home = (DonXuatFrame) parent;
        model = (DefaultTableModel) tblDanhSach.getModel();
        model.setColumnIdentifiers(tieuDe);
        thietLapTenSanPham();
    }

    /**
     * Thiết lập combobox tên sản phẩm
     */
    public void thietLapTenSanPham() {
        dsSanPham = new SanPhamDao().layDanhSachPhanTu();
        dsTenSanPham = new String[dsSanPham.size()];

        for (int i = 0; i < dsSanPham.size(); i++) {
            dsTenSanPham[i] = dsSanPham.get(i).getTenSanPham();
        }
        cbSanPham.setModel(new javax.swing.DefaultComboBoxModel(dsTenSanPham));
    }

    /**
     * Lấy thông tin nhận được
     * @param maNhanDuoc 
     */
    public void layThongTinNhanDuoc(String maNhanDuoc) {
        maDonXuat = maNhanDuoc;
        hienThi();
    }
    
    /**
     * Hiển thị bảng dữ liệu
     */
    public void hienThi() {
        dsCTDonXuat = new CTDonXuatDao().layDanhSachPhanTu(maDonXuat);
        model.setRowCount(0);
        for (CTDonXuat ptu : dsCTDonXuat) {
            model.addRow(new Object[] {
                model.getRowCount() + 1, ptu.getMaSanPham(), ptu.getTenSanPham(), ptu.getSoLuongXuat()
            });
        }
    }
    
    /**
     * Làm mới form nhập liệu
     */
    public void lamMoiForm() {
        cbSanPham.setSelectedIndex(0);
        cbSanPham.setEnabled(true);
        txtSoLuong.setText("");
        txtDonGia.setText("");
        viTri = -1;
        btnThemMoi.setEnabled(true);
        btnCapNhat.setEnabled(false);
        btnXoa.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbSanPham = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemMoi = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết đơn hàng nhập");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi tiết đơn hàng xuất");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setText("Sản phẩm");

        cbSanPham.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel3.setText("Số lượng xuất");

        txtSoLuong.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        btnThemMoi.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setEnabled(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblDanhSach.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setText("Đơn giá xuất");

        txtDonGia.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSoLuong))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        int soLuong = 0;
        float donGia = 0;
        String maSanPham = null;
        boolean isDone = true;

        if ("".equals(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống");
            isDone = false;
        } else {
            try {
                soLuong = Integer.parseInt(txtSoLuong.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng không đúng định dạng");
                isDone = false;
            }
        }
        
        if ("".equals(txtDonGia.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Đơn giá không được để trống");
            isDone = false;
        } else {
            try {
                donGia = Float.parseFloat(txtDonGia.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Đơn giá không đúng định dạng");
                isDone = false;
            }
        }
        
        int viTriSanPham = cbSanPham.getSelectedIndex();
        maSanPham = dsSanPham.get(viTriSanPham).getMaSanPham();
        
        if(isDone) {
            CTDonXuat ptu = new CTDonXuat(maDonXuat, maSanPham, soLuong, donGia);
            if(new CTDonXuatDao().themPhanTu(ptu)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
                hienThi();
                lamMoiForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Sản phẩm đã tồn tại");
            }
        }
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        viTri = tblDanhSach.getSelectedRow();
        
        if(viTri > -1) {
            btnCapNhat.setEnabled(true);
            btnXoa.setEnabled(true);
            btnThemMoi.setEnabled(false);
            
            CTDonXuat ptu = dsCTDonXuat.get(viTri);
            int index = 0;
            for (int i = 0; i < dsSanPham.size(); i++) {
                if(ptu.getMaSanPham().equals(dsSanPham.get(i).getMaSanPham())) {
                    index = i;
                    break;
                }
            }
            cbSanPham.setSelectedIndex(index);
            cbSanPham.setEnabled(false);
            txtSoLuong.setText("" + ptu.getSoLuongXuat());
            txtDonGia.setText("" + ptu.getDonGia());
        } else {
            btnCapNhat.setEnabled(false);
            btnXoa.setEnabled(false);
            btnThemMoi.setEnabled(true);
            lamMoiForm();
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int soLuong = 0;
        float donGia = 0;
        String maSanPham = null;
        boolean isDone = true;

        if ("".equals(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng không được để trống");
            isDone = false;
        } else {
            try {
                soLuong = Integer.parseInt(txtSoLuong.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số lượng không đúng định dạng");
                isDone = false;
            }
        }
        
        if ("".equals(txtDonGia.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Đơn giá không được để trống");
            isDone = false;
        } else {
            try {
                donGia = Float.parseFloat(txtDonGia.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Đơn giá không đúng định dạng");
                isDone = false;
            }
        }
        
        int viTriSanPham = cbSanPham.getSelectedIndex();
        maSanPham = dsSanPham.get(viTriSanPham).getMaSanPham();
        
        if(isDone) {
            CTDonXuat ptu = new CTDonXuat(maDonXuat, maSanPham, soLuong, donGia);
            if(new CTDonXuatDao().capNhatPhanTu(ptu)) {
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                hienThi();
                lamMoiForm();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xuất hiện lỗi");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int isXoa = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa?");
        
        if(isXoa == 0) {
            CTDonXuat ptu = dsCTDonXuat.get(viTri);
            if(new CTDonXuatDao().xoaPhanTu(ptu)) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                hienThi();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xuất hiện lỗi!");
            }
        }
        lamMoiForm();
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTDonXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTDonXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTDonXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTDonXuatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CTDonXuatFrame dialog = new CTDonXuatFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
