package views;

/**
 *
 * @author
 */
public class TrangChuFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuFrame
     */
    public TrangChuFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLNhanVien = new javax.swing.JButton();
        btnQLKhachHang = new javax.swing.JButton();
        btnQLNhaCC = new javax.swing.JButton();
        btnQLDonHang = new javax.swing.JButton();
        btnQLDonNhap = new javax.swing.JButton();
        btnQLDanhMucSanPham = new javax.swing.JButton();
        btnQLBanHang = new javax.swing.JButton();
        btnQLThuChi = new javax.swing.JButton();
        btnQLSanPham = new javax.swing.JButton();
        btnQLDonXuat = new javax.swing.JButton();
        btnQLTonKho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng siêu thị AEON");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý bán hàng siêu thị AEON");

        btnQLNhanVien.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLNhanVien.setText("Quản lý nhân viên");
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });

        btnQLKhachHang.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLKhachHang.setText("Quản lý khách hàng thân thiết");
        btnQLKhachHang.setToolTipText("");
        btnQLKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKhachHangActionPerformed(evt);
            }
        });

        btnQLNhaCC.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLNhaCC.setText("Quản lý nhà cung cấp");
        btnQLNhaCC.setToolTipText("");
        btnQLNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhaCCActionPerformed(evt);
            }
        });

        btnQLDonHang.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLDonHang.setText("Quản lý đơn hàng nhà cung cấp");
        btnQLDonHang.setToolTipText("");
        btnQLDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonHangActionPerformed(evt);
            }
        });

        btnQLDonNhap.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLDonNhap.setText("Quản lý đơn nhập hàng");
        btnQLDonNhap.setToolTipText("");
        btnQLDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonNhapActionPerformed(evt);
            }
        });

        btnQLDanhMucSanPham.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLDanhMucSanPham.setText("Quản lý danh mục sản phẩm");
        btnQLDanhMucSanPham.setToolTipText("");
        btnQLDanhMucSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDanhMucSanPhamActionPerformed(evt);
            }
        });

        btnQLBanHang.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLBanHang.setText("Quản lý bán hàng");
        btnQLBanHang.setToolTipText("");
        btnQLBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLBanHangActionPerformed(evt);
            }
        });

        btnQLThuChi.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLThuChi.setText("Quản lý tài chính thu chi");
        btnQLThuChi.setToolTipText("");

        btnQLSanPham.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLSanPham.setText("Quản lý sản phẩm");
        btnQLSanPham.setToolTipText("");
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });

        btnQLDonXuat.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLDonXuat.setText("Quản lý đơn xuất hàng");
        btnQLDonXuat.setToolTipText("");
        btnQLDonXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLDonXuatActionPerformed(evt);
            }
        });

        btnQLTonKho.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        btnQLTonKho.setText("Quản lý tồn kho");
        btnQLTonKho.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQLDonNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLDonXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLDanhMucSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLThuChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLSanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQLDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLDonXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLDanhMucSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQLThuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        new NhanVienFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNhanVienActionPerformed

    private void btnQLKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKhachHangActionPerformed
        new KhachHangFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLKhachHangActionPerformed

    private void btnQLDanhMucSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDanhMucSanPhamActionPerformed
        new DanhMucFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDanhMucSanPhamActionPerformed

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        new SanPhamFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void btnQLNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhaCCActionPerformed
        new NhaCungCapFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLNhaCCActionPerformed

    private void btnQLDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonHangActionPerformed
        new DonDatHangFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDonHangActionPerformed

    private void btnQLDonNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonNhapActionPerformed
        new DonNhapFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDonNhapActionPerformed

    private void btnQLDonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLDonXuatActionPerformed
        new DonXuatFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLDonXuatActionPerformed

    private void btnQLBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLBanHangActionPerformed
        new BanHangFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLBanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLBanHang;
    private javax.swing.JButton btnQLDanhMucSanPham;
    private javax.swing.JButton btnQLDonHang;
    private javax.swing.JButton btnQLDonNhap;
    private javax.swing.JButton btnQLDonXuat;
    private javax.swing.JButton btnQLKhachHang;
    private javax.swing.JButton btnQLNhaCC;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton btnQLThuChi;
    private javax.swing.JButton btnQLTonKho;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
